---
- hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install dependencies (RedHat).
      yum: name={{ item }} state=present
      when: ansible_os_family == 'RedHat'
      with_items:
        - cronie
        - epel-release

    - name: Install cron (Debian).
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

  roles:
    - role: ansible-role-certbot
      certbot_admin_email: email@example.com
      certbot_domains:
      - openmicroscopy.example.org
      certbot_create_args: "--standalone --test-cert"
      # We can't actually test letsencrypt without a public domain so
      # instead just check the playbooks syntax and that the cronjob is
      # installed
      certbot_create_if_missing: False
