---
- include: include-vars.yml

- include: install-with-package.yml
  when: not certbot_install_from_source

- include: install-from-source.yml
  when: certbot_install_from_source

- include: create-cert-standalone.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item

- include: renew-cron.yml
  when: certbot_auto_renew
